"""
Mutation command contract (spec §3.3).

This is the ONLY thing the LLM is ever allowed to emit. It never generates
the diagram, never writes ArchitectureState directly. Every command here
maps 1:1 to a Groq tool-calling function definition (see llm/groq_provider.py)
so the model is structurally constrained to this vocabulary.
"""
from __future__ import annotations

from typing import Annotated, Literal, Optional, Union

from pydantic import BaseModel, Field

from app.models.state import ConstraintType, Protocol, SyncAsync, TriggeredBy


class AddNodeCommand(BaseModel):
    op: Literal["add_node"] = "add_node"
    ref: str = Field(
        description="A short local alias you choose for this node (e.g. 'api_service'), "
        "used to wire edges to it later IN THIS SAME BATCH via add_edge.from_id/to_id. "
        "The real node id is generated by the server, not by you."
    )
    node_type: Literal["service", "database", "queue", "external_dependency", "infra_node"]
    name: str
    attributes: dict = Field(default_factory=dict)


class RemoveNodeCommand(BaseModel):
    op: Literal["remove_node"] = "remove_node"
    id: str


class UpdateNodeCommand(BaseModel):
    op: Literal["update_node"] = "update_node"
    id: str
    attributes: dict = Field(default_factory=dict)


class AddEdgeCommand(BaseModel):
    op: Literal["add_edge"] = "add_edge"
    from_id: str = Field(description="Either an existing node id, or a `ref` used by an add_node command earlier in this same batch.")
    to_id: str = Field(description="Either an existing node id, or a `ref` used by an add_node command earlier in this same batch.")
    protocol: Protocol
    sync_async: SyncAsync
    notes: Optional[str] = None


class RemoveEdgeCommand(BaseModel):
    op: Literal["remove_edge"] = "remove_edge"
    id: str


class SetConstraintCommand(BaseModel):
    op: Literal["set_constraint"] = "set_constraint"
    type: ConstraintType
    value: str


class AnnotateDecisionCommand(BaseModel):
    op: Literal["annotate_decision"] = "annotate_decision"
    text: str
    rationale: str
    triggered_by: TriggeredBy = TriggeredBy.ai_recommendation


MutationCommand = Annotated[
    Union[
        AddNodeCommand,
        RemoveNodeCommand,
        UpdateNodeCommand,
        AddEdgeCommand,
        RemoveEdgeCommand,
        SetConstraintCommand,
        AnnotateDecisionCommand,
    ],
    Field(discriminator="op"),
]


class CommandValidationError(BaseModel):
    """Structured error handed back to the LLM so it can retry (spec §3.3:
    'never silently drop an invalid command')."""

    command_index: int
    op: str
    error: str


class InterviewTurnOutput(BaseModel):
    """The model's structured output for every interview/edit/tier turn.

    Control flow is structured even though `question`/`summary` are free
    text — the model can only ever be in one of three modes: still
    gathering requirements, editing the current architecture, or
    generating an alternative tier from the same underlying requirements
    (spec §6 Phase 3).
    """

    action: Literal["ask_question", "propose_architecture", "generate_tier"]
    question: Optional[str] = None
    quick_replies: Optional[list[str]] = None  # short tappable answers for `question`, e.g. ["$0", "$50/mo", "$500/mo"] — omit for genuinely open-ended questions
    commands: Optional[list[MutationCommand]] = None
    summary: Optional[str] = None  # short natural-language note for the chat log
    tier_label: Optional[str] = None  # required when action == "generate_tier", e.g. "$0 Student Tier"
