"""
Mutation command contract (spec §3.3).

This is the ONLY thing the LLM is ever allowed to emit. It never generates
the diagram, never writes ArchitectureState directly. Every command here
maps 1:1 to a Groq tool-calling function definition (see llm/groq_provider.py)
so the model is structurally constrained to this vocabulary.
"""
from __future__ import annotations

from typing import Annotated, Literal, Optional, Union

from pydantic import BaseModel, Field

from app.models.state import ConstraintType, Protocol, SyncAsync, TriggeredBy


class AddNodeCommand(BaseModel):
    op: Literal["add_node"] = "add_node"
    ref: str = Field(
        description="A short local alias you choose for this node (e.g. 'api_service'), "
        "used to wire edges to it later IN THIS SAME BATCH via add_edge.from_id/to_id. "
        "The real node id is generated by the server, not by you."
    )
    node_type: Literal["service", "database", "queue", "external_dependency", "infra_node"]
    name: str
    attributes: dict = Field(default_factory=dict)


class RemoveNodeCommand(BaseModel):
    op: Literal["remove_node"] = "remove_node"
    id: str


class UpdateNodeCommand(BaseModel):
    op: Literal["update_node"] = "update_node"
    id: str
    attributes: dict = Field(default_factory=dict)


class AddEdgeCommand(BaseModel):
    op: Literal["add_edge"] = "add_edge"
    from_id: str = Field(description="Either an existing node id, or a `ref` used by an add_node command earlier in this same batch.")
    to_id: str = Field(description="Either an existing node id, or a `ref` used by an add_node command earlier in this same batch.")
    protocol: Protocol
    sync_async: SyncAsync
    notes: Optional[str] = None


class RemoveEdgeCommand(BaseModel):
    op: Literal["remove_edge"] = "remove_edge"
    id: str


class SetConstraintCommand(BaseModel):
    op: Literal["set_constraint"] = "set_constraint"
    type: ConstraintType
    value: str


class AnnotateDecisionCommand(BaseModel):
    op: Literal["annotate_decision"] = "annotate_decision"
    text: str
    rationale: str
    triggered_by: TriggeredBy = TriggeredBy.ai_recommendation


MutationCommand = Annotated[
    Union[
        AddNodeCommand,
        RemoveNodeCommand,
        UpdateNodeCommand,
        AddEdgeCommand,
        RemoveEdgeCommand,
        SetConstraintCommand,
        AnnotateDecisionCommand,
    ],
    Field(discriminator="op"),
]


class ApplyCommandsRequest(BaseModel):
    """Body for POST .../commands — a manual edit from the canvas (add a
    node via the palette, drag-connect two nodes, delete something)
    constructing the exact same MutationCommand shapes the LLM already
    produces, validated by the exact same discriminated union and the
    exact same code path (services/mutation_engine.py's apply_commands) —
    the "AI never draws the diagram directly" guarantee applies equally
    to a human drawing it directly, because both origins produce
    identical, identically-validated commands."""

    commands: list[MutationCommand]


class CommandValidationError(BaseModel):
    """Structured error handed back to the LLM so it can retry (spec §3.3:
    'never silently drop an invalid command')."""

    command_index: int
    op: str
    error: str


class InterviewTurnOutput(BaseModel):
    """The model's structured output for every interview/edit/tier turn.

    Control flow is structured even though `question`/`summary` are free
    text — the model can only ever be in one of three modes: still
    gathering requirements, editing the current architecture, or
    generating an alternative tier from the same underlying requirements
    (spec §6 Phase 3).
    """

    action: Literal["ask_question", "propose_architecture", "generate_tier"]
    question: Optional[str] = None
    quick_replies: Optional[list[str]] = None  # short tappable answers for `question`, e.g. ["$0", "$50/mo", "$500/mo"] — omit for genuinely open-ended questions
    commands: Optional[list[MutationCommand]] = None
    summary: Optional[str] = None  # short natural-language note for the chat log
    tier_label: Optional[str] = None  # required when action == "generate_tier", e.g. "$0 Student Tier"
    # 1-3 short bullets, distinct from `question`/`summary`: for
    # ask_question, the real tradeoff behind the question about to be
    # asked (framed BEFORE the user answers, not narrated after); for
    # propose_architecture, the specific already-stated constraints (real
    # numbers/values, not generic advice) that drove the key choices just
    # made. Always omit rather than invent one when there's no genuine
    # tradeoff/driving constraint yet (a simple first question, or an
    # edit with an obvious single cause) — see prompts.py for the full rule.
    reasoning: Optional[list[str]] = None


class GatherQuestionOutput(BaseModel):
    """Structured output for ONE requirements-gathering question — a
    deliberately much smaller sibling of InterviewTurnOutput, used only
    before a project's first design exists (see services/interview.py's
    REQUIRED_CONSTRAINT_ORDER checklist).

    Two real bugs, found live, drove this split: (1) the interview used to
    silently ask the same question twice, because nothing was actually
    persisted from an answer until the LLM finally proposed a design — it
    only ever lived in raw chat history, which the token-budget trim can
    (and did) drop on a long interview; (2) every single gathering
    question paid the full cost of InterviewTurnOutput's whole 7-variant
    command schema plus the entire edit/tier rulebook, neither of which a
    plain "what's your budget" question needs, which is why a long
    interview could hit Groq's rate limit before a design was ever
    proposed. Recording an answer as a real, versioned constraint is now
    handled deterministically in code (services/interview.py), not by the
    model — this schema's only job is phrasing the NEXT question (for a
    constraint type code has already decided on, in a fixed order that
    asks budget LAST) naturally, with good quick_replies.
    """

    question: str
    quick_replies: Optional[list[str]] = None  # short tappable answers, e.g. ["$0", "$50/mo", "$500/mo", "Not sure"] — omit for genuinely open-ended questions
    # 1-2 bullets, only when a real tradeoff already exists between what's
    # already known and this question — never generic, omit otherwise
    # (most gathering questions are a simple, unrelated next fact and have
    # none — see InterviewTurnOutput.reasoning for the fuller rule this
    # mirrors).
    reasoning: Optional[list[str]] = None
