import type { ArchNode } from "./types";

// Short, plain-English explanations of what each component type actually
// does, plus a few real-world technologies that fill that role — so
// clicking a node teaches the "why", not just the "what it's labeled".
// Keyed by `${node_kind}:${type}`, mirroring the discriminated node types
// in backend/app/models/state.py. This is presentation-only reference
// content (never sent to or generated by the LLM) — safe to expand freely.

export interface ComponentInfo {
  description: string;
  examples?: string[];
}

const INFO: Record<string, ComponentInfo> = {
  // --- services --------------------------------------------------------
  "service:gateway": {
    description:
      "The front door for external traffic: routes incoming requests to the right internal service, and commonly handles auth checks, rate limiting, and request validation in one place before anything reaches your business logic.",
    examples: ["Kong", "NGINX", "AWS API Gateway", "a custom Express/FastAPI gateway"],
  },
  "service:service": {
    description: "A backend service implementing core business logic, exposed over an API for the frontend or other services to call.",
  },
  "service:worker": {
    description:
      "Runs background jobs pulled off a queue instead of inline in a request — the things too slow or unreliable to make a user wait on, like sending emails, resizing images, or generating reports.",
    examples: ["Celery", "Sidekiq", "BullMQ", "AWS Lambda (event-driven)"],
  },
  "service:frontend": {
    description: "The client-facing application users interact with directly — renders the UI and calls backend APIs over the network.",
    examples: ["React / Next.js", "React Native", "Flutter"],
  },
  "service:edge_cdn": {
    description:
      "Serves the frontend's static assets (JS, CSS, images) from edge locations physically close to users, so pages load fast anywhere without every request hitting your origin server.",
    examples: ["Cloudflare", "AWS CloudFront", "Vercel Edge Network", "Fastly"],
  },

  // --- databases ---------------------------------------------------------
  "database:relational": {
    description: "Stores structured data with an enforced schema and relationships, with strong consistency and transactions (ACID) — the safe default for most business data.",
    examples: ["PostgreSQL", "MySQL", "Amazon Aurora"],
  },
  "database:document": {
    description: "Stores flexible, JSON-like documents without a fixed schema — a good fit when records vary in shape or evolve often.",
    examples: ["MongoDB", "Firestore", "Amazon DocumentDB"],
  },
  "database:keyvalue": {
    description:
      "Extremely fast lookups by key, usually held in memory — used for caching, session storage, and rate-limit counters, and sometimes as a lightweight primary store.",
    examples: ["Redis", "Memcached", "DynamoDB"],
  },
  "database:search": {
    description: "Indexes data for fast full-text search and faceted filtering that a relational database can't do efficiently at scale.",
    examples: ["Elasticsearch", "OpenSearch", "Algolia", "Meilisearch"],
  },
  "database:graph": {
    description: "Stores entities and the relationships between them as a graph, optimized for traversal queries like recommendations, social graphs, or fraud detection.",
    examples: ["Neo4j", "Amazon Neptune"],
  },

  // --- queues --------------------------------------------------------------
  "queue:queue": {
    description:
      "Holds jobs for asynchronous processing so a producer can return immediately while a worker handles the task later — smooths out traffic spikes and decouples the two sides.",
    examples: ["AWS SQS", "RabbitMQ", "Google Cloud Tasks"],
  },
  "queue:pubsub": {
    description: "Broadcasts one event to multiple independent subscribers at once — lets several services react to the same event without being directly coupled to each other.",
    examples: ["Google Pub/Sub", "AWS SNS", "Redis Pub/Sub"],
  },
  "queue:stream": {
    description:
      "An ordered, replayable log of events that multiple consumers can read at their own pace — the backbone of event-driven pipelines and real-time stream processing.",
    examples: ["Apache Kafka", "AWS Kinesis", "Redpanda"],
  },

  // --- external dependencies ------------------------------------------------
  "external_dependency:third_party_api": {
    description: "An external service this system calls but doesn't control — its downtime or rate limits directly become this system's problem.",
  },
  "external_dependency:payment": {
    description: "Handles payment processing and card charges so the system never has to store or secure raw card data itself (PCI compliance).",
    examples: ["Stripe", "PayPal", "Braintree"],
  },
  "external_dependency:market_data": {
    description: "Supplies real-time or delayed financial market data (prices, quotes, fundamentals) the system depends on.",
    examples: ["Alpha Vantage", "IEX Cloud", "Polygon.io"],
  },
  "external_dependency:auth_provider": {
    description: "Handles user identity — login, sessions, SSO, MFA — so the system doesn't build and secure its own auth stack from scratch.",
    examples: ["Auth0", "Clerk", "AWS Cognito", "Firebase Auth"],
  },
  "external_dependency:storage": {
    description: "Externally managed storage for files and blobs the system relies on but doesn't operate itself.",
    examples: ["AWS S3", "Google Cloud Storage"],
  },

  // --- infra nodes -----------------------------------------------------------
  "infra_node:cdn": {
    description:
      "Caches and serves static assets from edge locations close to users, cutting latency and offloading traffic that would otherwise all hit the origin server.",
    examples: ["Cloudflare", "AWS CloudFront", "Fastly", "Akamai"],
  },
  "infra_node:load_balancer": {
    description:
      "Spreads incoming traffic across multiple instances of a service so no single instance is overwhelmed, and automatically routes around instances that fail health checks.",
    examples: ["AWS ALB / NLB", "NGINX", "HAProxy", "Envoy"],
  },
  "infra_node:api_gateway": {
    description:
      "A single entry point that routes external requests to the right backend service, typically bundling in auth, rate limiting, and request/response transformation.",
    examples: ["Kong", "AWS API Gateway", "Apigee", "NGINX"],
  },
  "infra_node:object_storage": {
    description: "Durable, cheap, highly scalable storage for unstructured files — images, videos, backups, exports — accessed over HTTP rather than a filesystem.",
    examples: ["AWS S3", "Google Cloud Storage", "Cloudflare R2"],
  },
  "infra_node:container_runtime": {
    description:
      "Schedules, scales, restarts, and health-checks containerized service instances automatically, instead of manually deploying services to fixed servers.",
    examples: ["Kubernetes", "AWS ECS / Fargate", "Docker Swarm"],
  },
  "infra_node:observability": {
    description:
      "Collects logs, metrics, and traces from every service so failures and performance regressions can be detected and diagnosed quickly instead of flying blind.",
    examples: ["Datadog", "Grafana + Prometheus", "New Relic", "Honeycomb"],
  },
};

const ROLE_NOTE: Record<string, string> = {
  cache: " Deployed here as a cache in front of the primary — absorbs read traffic so the primary doesn't take the full load.",
  replica: " Deployed here as a read replica of the primary — serves read traffic to improve throughput and availability.",
};

export function getComponentInfo(node: ArchNode): ComponentInfo | null {
  const base = INFO[`${node.node_kind}:${node.type}`];
  if (!base) return null;

  const role = typeof node.role === "string" ? node.role : undefined;
  if (node.node_kind === "database" && role && ROLE_NOTE[role]) {
    return { ...base, description: base.description + ROLE_NOTE[role] };
  }
  return base;
}
