import type { ArchNode, NodeKind } from "./types";

// Short, plain-English explanations of what each component type actually
// does, plus a few real-world technologies that fill that role — so
// clicking a node teaches the "why", not just the "what it's labeled".
// Keyed by `${node_kind}:${type}`, mirroring the discriminated node types
// in backend/app/models/state.py. This is presentation-only reference
// content (never sent to or generated by the LLM) — safe to expand freely.
//
// `label` (added alongside the drag-and-drop component palette — see
// ComponentPalette.tsx) is this same catalog's single addition for that
// UI: a short, human title for the type ("Relational Database", not the
// raw "relational"), reusing this file as the one place a component
// type's name/description/examples all live rather than a second,
// parallel label table that could drift from this one.

export interface ComponentInfo {
  label: string;
  description: string;
  examples?: string[];
}

const INFO: Record<string, ComponentInfo> = {
  // --- services --------------------------------------------------------
  "service:gateway": {
    label: "API Gateway Service",
    description:
      "The front door for external traffic: routes incoming requests to the right internal service, and commonly handles auth checks, rate limiting, and request validation in one place before anything reaches your business logic.",
    examples: ["Kong", "NGINX", "AWS API Gateway", "a custom Express/FastAPI gateway"],
  },
  "service:service": {
    label: "Backend Service",
    description: "A backend service implementing core business logic, exposed over an API for the frontend or other services to call.",
  },
  "service:worker": {
    label: "Background Worker",
    description:
      "Runs background jobs pulled off a queue instead of inline in a request — the things too slow or unreliable to make a user wait on, like sending emails, resizing images, or generating reports.",
    examples: ["Celery", "Sidekiq", "BullMQ", "AWS Lambda (event-driven)"],
  },
  "service:frontend": {
    label: "Frontend App",
    description: "The client-facing application users interact with directly — renders the UI and calls backend APIs over the network.",
    examples: ["React / Next.js", "React Native", "Flutter"],
  },
  "service:edge_cdn": {
    label: "Edge-Rendered Frontend",
    description:
      "Serves the frontend's static assets (JS, CSS, images) from edge locations physically close to users, so pages load fast anywhere without every request hitting your origin server.",
    examples: ["Cloudflare", "AWS CloudFront", "Vercel Edge Network", "Fastly"],
  },
  "service:scheduler": {
    label: "Scheduled Job",
    description: "Triggers jobs on a fixed schedule (cron-like) — independent of a queue or an incoming event, it just runs on time.",
    examples: ["Apache Airflow", "cron", "AWS EventBridge Scheduler", "Temporal"],
  },
  "service:ml_inference": {
    label: "ML Inference Service",
    description: "Serves predictions from a trained model over an API — usually its own scaling profile (often GPU-backed) separate from regular backend services.",
    examples: ["TorchServe", "AWS SageMaker endpoint", "NVIDIA Triton", "Ray Serve"],
  },
  "service:realtime": {
    label: "Realtime Service",
    description: "Holds persistent connections open to push live updates to clients — chat, notifications, multiplayer/collab state — a distinct scaling profile (concurrent connections, not just req/s) from a normal request/response service.",
    examples: ["Socket.IO", "Pusher", "Ably", "AWS API Gateway WebSockets"],
  },

  // --- databases ---------------------------------------------------------
  "database:relational": {
    label: "Relational Database",
    description: "Stores structured data with an enforced schema and relationships, with strong consistency and transactions (ACID) — the safe default for most business data.",
    examples: ["PostgreSQL", "MySQL", "Amazon Aurora"],
  },
  "database:document": {
    label: "Document Database",
    description: "Stores flexible, JSON-like documents without a fixed schema — a good fit when records vary in shape or evolve often.",
    examples: ["MongoDB", "Firestore", "Amazon DocumentDB"],
  },
  "database:keyvalue": {
    label: "Key-Value Store",
    description:
      "Extremely fast lookups by key, usually held in memory — used for caching, session storage, and rate-limit counters, and sometimes as a lightweight primary store.",
    examples: ["Redis", "Memcached", "DynamoDB"],
  },
  "database:search": {
    label: "Search Index",
    description: "Indexes data for fast full-text search and faceted filtering that a relational database can't do efficiently at scale.",
    examples: ["Elasticsearch", "OpenSearch", "Algolia", "Meilisearch"],
  },
  "database:graph": {
    label: "Graph Database",
    description: "Stores entities and the relationships between them as a graph, optimized for traversal queries like recommendations, social graphs, or fraud detection.",
    examples: ["Neo4j", "Amazon Neptune"],
  },
  "database:time_series": {
    label: "Time-Series Database",
    description: "Optimized for high-volume, timestamped writes and efficient range queries over time — metrics, sensor readings, application events.",
    examples: ["InfluxDB", "TimescaleDB", "Prometheus"],
  },
  "database:columnar": {
    label: "Analytical Warehouse",
    description: "Column-oriented storage built for analytical (OLAP) queries scanning large datasets — a data warehouse, not the system's transactional store.",
    examples: ["Snowflake", "Google BigQuery", "Amazon Redshift", "ClickHouse"],
  },
  "database:vector": {
    label: "Vector Database",
    description: "Indexes embeddings for similarity search — the retrieval half of RAG, semantic search, and recommendation systems, where a lookup means \"find the nearest meaning\" instead of an exact match.",
    examples: ["Pinecone", "Weaviate", "Qdrant", "Chroma", "pgvector"],
  },

  // --- queues --------------------------------------------------------------
  "queue:queue": {
    label: "Work Queue",
    description:
      "Holds jobs for asynchronous processing so a producer can return immediately while a worker handles the task later — smooths out traffic spikes and decouples the two sides.",
    examples: ["AWS SQS", "RabbitMQ", "Google Cloud Tasks"],
  },
  "queue:pubsub": {
    label: "Pub/Sub Topic",
    description: "Broadcasts one event to multiple independent subscribers at once — lets several services react to the same event without being directly coupled to each other.",
    examples: ["Google Pub/Sub", "AWS SNS", "Redis Pub/Sub"],
  },
  "queue:stream": {
    label: "Event Stream",
    description:
      "An ordered, replayable log of events that multiple consumers can read at their own pace — the backbone of event-driven pipelines and real-time stream processing.",
    examples: ["Apache Kafka", "AWS Kinesis", "Redpanda"],
  },

  // --- external dependencies ------------------------------------------------
  "external_dependency:third_party_api": {
    label: "Third-Party API",
    description: "An external service this system calls but doesn't control — its downtime or rate limits directly become this system's problem.",
  },
  "external_dependency:payment": {
    label: "Payment Provider",
    description: "Handles payment processing and card charges so the system never has to store or secure raw card data itself (PCI compliance).",
    examples: ["Stripe", "PayPal", "Braintree"],
  },
  "external_dependency:market_data": {
    label: "Market Data Provider",
    description: "Supplies real-time or delayed financial market data (prices, quotes, fundamentals) the system depends on.",
    examples: ["Alpha Vantage", "IEX Cloud", "Polygon.io"],
  },
  "external_dependency:auth_provider": {
    label: "Auth Provider",
    description: "Handles user identity — login, sessions, SSO, MFA — so the system doesn't build and secure its own auth stack from scratch.",
    examples: ["Auth0", "Clerk", "AWS Cognito", "Firebase Auth"],
  },
  "external_dependency:storage": {
    label: "External Storage",
    description: "Externally managed storage for files and blobs the system relies on but doesn't operate itself.",
    examples: ["AWS S3", "Google Cloud Storage"],
  },
  "external_dependency:notification_provider": {
    label: "Notification Provider",
    description: "Sends email, SMS, or push notifications on the system's behalf instead of the system operating its own delivery infrastructure.",
    examples: ["Twilio", "SendGrid", "Postmark", "Firebase Cloud Messaging"],
  },
  "external_dependency:analytics": {
    label: "Analytics Provider",
    description: "A third-party product-analytics or telemetry destination the system sends user/usage events to.",
    examples: ["Segment", "Mixpanel", "Amplitude", "PostHog"],
  },
  "external_dependency:feature_flags": {
    label: "Feature Flags Provider",
    description: "Controls which users see which features at runtime — gradual rollouts, A/B tests, and instant kill-switches without a redeploy.",
    examples: ["LaunchDarkly", "Flagsmith", "Unleash", "GrowthBook"],
  },

  // --- infra nodes -----------------------------------------------------------
  "infra_node:cdn": {
    label: "CDN",
    description:
      "Caches and serves static assets from edge locations close to users, cutting latency and offloading traffic that would otherwise all hit the origin server.",
    examples: ["Cloudflare", "AWS CloudFront", "Fastly", "Akamai"],
  },
  "infra_node:load_balancer": {
    label: "Load Balancer",
    description:
      "Spreads incoming traffic across multiple instances of a service so no single instance is overwhelmed, and automatically routes around instances that fail health checks.",
    examples: ["AWS ALB / NLB", "NGINX", "HAProxy", "Envoy"],
  },
  "infra_node:api_gateway": {
    label: "API Gateway",
    description:
      "A single entry point that routes external requests to the right backend service, typically bundling in auth, rate limiting, and request/response transformation.",
    examples: ["Kong", "AWS API Gateway", "Apigee", "NGINX"],
  },
  "infra_node:object_storage": {
    label: "Object Storage",
    description: "Durable, cheap, highly scalable storage for unstructured files — images, videos, backups, exports — accessed over HTTP rather than a filesystem.",
    examples: ["AWS S3", "Google Cloud Storage", "Cloudflare R2"],
  },
  "infra_node:container_runtime": {
    label: "Container Runtime",
    description:
      "Schedules, scales, restarts, and health-checks containerized service instances automatically, instead of manually deploying services to fixed servers.",
    examples: ["Kubernetes", "AWS ECS / Fargate", "Docker Swarm"],
  },
  "infra_node:observability": {
    label: "Observability Stack",
    description:
      "Collects logs, metrics, and traces from every service so failures and performance regressions can be detected and diagnosed quickly instead of flying blind.",
    examples: ["Datadog", "Grafana + Prometheus", "New Relic", "Honeycomb"],
  },
  "infra_node:dns": {
    label: "DNS",
    description: "Resolves domain names to IP addresses and can route traffic at the DNS layer itself — latency-based routing, health-check failover, geo-routing.",
    examples: ["Amazon Route 53", "Cloudflare DNS", "NS1"],
  },
  "infra_node:firewall_waf": {
    label: "Firewall / WAF",
    description: "Filters malicious or malformed traffic (SQLi, XSS, known bad actors) before it ever reaches the application.",
    examples: ["AWS WAF", "Cloudflare WAF", "ModSecurity"],
  },
  "infra_node:secrets_manager": {
    label: "Secrets Manager",
    description: "Centrally stores, versions, and rotates credentials and API keys, instead of hardcoding them into service config or source.",
    examples: ["AWS Secrets Manager", "HashiCorp Vault", "Doppler"],
  },
  "infra_node:service_mesh": {
    label: "Service Mesh",
    description: "Manages service-to-service traffic at the network layer — mTLS, retries, timeouts, circuit breaking — without changes to application code.",
    examples: ["Istio", "Linkerd", "AWS App Mesh"],
  },
};

/** Every addable (node_kind, type) pair for one kind, in the same order
 * declared above — used to build the component palette's tiles for a
 * given tab. Grouped/ordered here already, so no separate ordering table
 * to keep in sync. */
export function listComponentTypes(kind: NodeKind): { type: string; info: ComponentInfo }[] {
  const prefix = `${kind}:`;
  return Object.entries(INFO)
    .filter(([key]) => key.startsWith(prefix))
    .map(([key, info]) => ({ type: key.slice(prefix.length), info }));
}

const ROLE_NOTE: Record<string, string> = {
  cache: " Deployed here as a cache in front of the primary — absorbs read traffic so the primary doesn't take the full load.",
  replica: " Deployed here as a read replica of the primary — serves read traffic to improve throughput and availability.",
};

export function getComponentInfo(node: ArchNode): ComponentInfo | null {
  const base = INFO[`${node.node_kind}:${node.type}`];
  if (!base) return null;

  const role = typeof node.role === "string" ? node.role : undefined;
  if (node.node_kind === "database" && role && ROLE_NOTE[role]) {
    return { ...base, description: base.description + ROLE_NOTE[role] };
  }
  return base;
}
